<a href="https://colab.research.google.com/github/hotieunguyenbaogpastro10/demo-github-actions/blob/main/Buoi1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!pip install numpy

import numpy as np

my_list=[1,9,15,39]
print('Python list:',my_list)
my_numpy_array=np.array(my_list)
print('Numpy array:',my_numpy_array)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]


In [5]:
a=np.array([1,9,15,39])
print(a)

[ 1  9 15 39]


In [6]:
c=np.array([(1,2,3),
            (4,5,6)
            ])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [7]:
d=np.array([
          [[1.,2.,3.],[4.,5.,6.]],
          [[7.,8.,9.,],[10,11,12]]
])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [8]:
e = np.zeros((2,2))
f=np.ones((3,3))
print('Zero matrix:\n',e)
print('One matrix\n',f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
e=np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
f=e.reshape(3,2)
print(f)
g=np.array([[[1.,2.,3.],[4.,5.,6.]],
           [[7.,8.,9.],[10.,11.,12.]]
           ])
print(g)
print(g.shape)
h=g.reshape(3,4)
print('reshape(3,4)\n',h)
j=g.reshape(3,2,2)
print('reshape(3,2,2)\n',j)
k=g.reshape(2,3,2)
print('reshape(2,3,2)\n',k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape(3,4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape(3,2,2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape(2,3,2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


In [10]:
e=np.array([[1.,2.,3.],[4.,5.,6.]])
f=e.flatten()
print(f)
g=np.array([[[1.,2.,3.],[4.,5.,6.]],
           [[7.,8.,9.],[10.,11.,12.]]
           ])
j=g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [11]:
f=np.array([1.,2.,3.])
g=np.array([4.,5.,6.])
h_stack=np.hstack((f,g))
print('Honrizontal Append\n',h_stack)
v_stack=np.vstack((f,g))
print('Vertical Append\n',v_stack)

Honrizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [13]:
a=np.random.randint(100,size=(5,))
print('Random 1-D array\n',a)
b=np.random.randint(100,size=(3,4))
print('Random 2-D array\n',b)
c=np.random.randint(100,size=(3,4,3))
print('Random 3-D array\n',c)

Random 1-D array
 [ 7 69 37 70 36]
Random 2-D array
 [[ 7 75 54 88]
 [62 75 18 78]
 [75 14 42  6]]
Random 3-D array
 [[[67 21 38]
  [25 80 29]
  [ 3 88 89]
  [83 54 39]]

 [[78 41 37]
  [68 62  6]
  [30  2 79]
  [29 68 66]]

 [[47 78 10]
  [99 22 68]
  [62 74  9]
  [81  6 24]]]


In [14]:
a=np.random.rand(5)
print('Random 1-D array\n',a)
b=np.random.rand(3,4)
print('Random 2-D array\n',b)
c=np.random.rand(3,4,3)
print('Random 3-D array\n',c)

Random 1-D array
 [0.03844696 0.71032964 0.37081009 0.59292991 0.2165534 ]
Random 2-D array
 [[0.39593415 0.25263922 0.0948434  0.19190693]
 [0.26079944 0.6913608  0.89485346 0.85585821]
 [0.42980267 0.98383879 0.43791223 0.02753837]]
Random 3-D array
 [[[0.54971014 0.56895221 0.85820436]
  [0.43335246 0.96155647 0.72795845]
  [0.0711554  0.3938414  0.14141621]
  [0.02319658 0.53151625 0.00927112]]

 [[0.88445251 0.32222757 0.8144336 ]
  [0.61819276 0.44116958 0.68576088]
  [0.94493462 0.01064411 0.28829314]
  [0.48002157 0.10482608 0.32426452]]

 [[0.72970305 0.56731017 0.34397926]
  [0.98417402 0.97846832 0.81968175]
  [0.86181277 0.79639079 0.1993971 ]
  [0.65169274 0.17215282 0.4677846 ]]]


In [15]:
a=np.random.normal(5,0.5,10)
print(a)

[3.65930572 5.35307144 3.73435827 4.70568833 5.30419657 4.93636113
 4.96836171 5.32774875 4.48568232 4.17455263]


In [16]:
a=np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)
b=np.random.choice([2,4,6,8,10,12,14,16,18,20],size=(3,5))
print(b)

18
[[18  4 20  8  4]
 [ 4  2  8 14 16]
 [10 16 20 20  6]]


In [17]:
A=np.matrix(np.ones((5,5)))
print('The matrix\n',A)
np.array(A)[2]=2
print('Change values of third row with array\n',A)
np.asarray(A)[2]=2
print('Change values of third row with asarray\n',A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
a=np.arange(1,20)
print(a)
b=np.arange(1,20,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [19]:
a=np.linspace(1.,5.,num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [20]:
a=np.array([(1,2,3),(4,5,6)])
print(a)
print('first row:',a[0])
print('second row:',a[1])
print('Second column',a[:,1])
print('first column',a[:,0])
print('First two values of second row:',a[1,:2])

[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column [2 5]
first column [1 4]
First two values of second row: [4 5]


In [22]:
!pip install pandas

import pandas as pd
a=pd.Series([1.,2.,3.])
print(a)
print('First value:',a[0])
b=pd.Series([1.,2.,3.],index=['a','b','c'])
print(b)
print('First value:',b['a'])
calories={"day1":420,"day2":380,"day3":390}
myvar=pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


In [23]:
h=np.array([[1,2],[3,4]])
df_h=pd.DataFrame(h)
print('DataFrame:\n',df_h)
numpy_h=np.array(df_h)
print('Numpy array:\n',numpy_h)

DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [24]:
dic={'Name':['John','Smith'],'Age':[30,40]}
df_dic=pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [25]:
r=np.random.randn(20,4)
df=pd.DataFrame(r,columns=['so1','so2','so3','so4'])
print(df.head())

        so1       so2       so3       so4
0  0.319410 -0.759487  0.454161  0.627712
1  0.205290  0.776157  0.977256 -0.233898
2 -0.854259 -0.250821 -0.145669  1.495620
3 -0.629103  1.055374  1.026889 -0.127564
4  0.205591 -0.173988  0.356030  1.490412


In [26]:
r=np.random.randn(20,4)
df=pd.DataFrame(r,columns=['so1','so2','so3','so4'])
print(df.head())
print('Chon cot so1\n',df['so1'])
print('Chon nhieu dong\n',df[0:3])
print('Chon nhieu cot\n',df[['so1','so3']])
print('Chon nhieu dong,nhieu cot\n',df.iloc[:3,:2])
df=df.drop(columns=['so1','so4'])
print(df)

        so1       so2       so3       so4
0  0.042805 -0.216582  0.417596 -0.614669
1 -0.312991 -0.670950 -1.337978  1.356208
2  1.147305 -1.783343  0.322793 -1.769762
3  0.203245 -0.715090  0.033247  0.979612
4  0.785462  0.156868 -0.108990  0.511489
Chon cot so1
 0     0.042805
1    -0.312991
2     1.147305
3     0.203245
4     0.785462
5     0.675471
6    -0.846096
7     0.801183
8    -0.761297
9    -2.578269
10    0.849199
11    0.498661
12    0.612884
13    0.394483
14   -0.766447
15    0.460170
16   -0.662667
17   -1.874367
18   -0.305550
19    0.753462
Name: so1, dtype: float64
Chon nhieu dong
         so1       so2       so3       so4
0  0.042805 -0.216582  0.417596 -0.614669
1 -0.312991 -0.670950 -1.337978  1.356208
2  1.147305 -1.783343  0.322793 -1.769762
Chon nhieu cot
          so1       so3
0   0.042805  0.417596
1  -0.312991 -1.337978
2   1.147305  0.322793
3   0.203245  0.033247
4   0.785462 -0.108990
5   0.675471  0.139884
6  -0.846096  0.218251
7   0.801183  0.798720


In [ ]:
df1=pd.DataFrame({'Name':['John','Smith','Paul'],
                 'Age':[25,30,50]
                 },index=[0,1,2])
df2=pd.DataFrame({'Name':['Adam','Smith','Paul'],
                 'Age':[25,30,50]
                 },index=[0,1,2])